# NumPy Library

In [3]:
import numpy as np
   
  

In [6]:
arr = np.array([1,2,3,4,5,6,7,8])

print(arr)
print(type(arr))

[1 2 3 4 5 6 7 8]
<class 'numpy.ndarray'>


In [7]:
arr = np.array((1,2,3,4,5,6,7,8))

print(arr)

print(type(arr))

[1 2 3 4 5 6 7 8]
<class 'numpy.ndarray'>


# Dimensions in array

In [9]:
arr = np.array(20)

print(arr)

print(type(arr))
print(arr.ndim)

20
<class 'numpy.ndarray'>
0


# 1 D array

In [12]:
arr = np.array([1,2,3,4,5,6,7,8])

print(arr)

print(arr.ndim)

print(type(arr))

[1 2 3 4 5 6 7 8]
1
<class 'numpy.ndarray'>


# 2 D array

In [14]:
arr = np.array([[1,3,4,5,6],[5,6,7,8,9]])
print(arr)
print(arr.ndim)

[[1 3 4 5 6]
 [5 6 7 8 9]]
2


In [16]:
arr = np.array([[1,3,4,5,6,],[5,6,7,8,9]])
print(arr)
print(arr.ndim)

[[1 3 4 5 6]
 [5 6 7 8 9]]
2


# 3D araay

In [18]:
arr = np.array([[[1,3,4,5,6,],[5,6,7,8,9],[65,44,55,66,66]]])
print(arr)
print(arr.ndim)

[[[ 1  3  4  5  6]
  [ 5  6  7  8  9]
  [65 44 55 66 66]]]
3


In [21]:
ara = np.array([1,2,3,4], ndmin=5)

print(arr)

print("number of dimensions ", arr.ndim)

[[[ 1  3  4  5  6]
  [ 5  6  7  8  9]
  [65 44 55 66 66]]]
number of dimensions  3


# indexing in numpy array

In [22]:
arr = np.array([1,2,3,4])
print(arr[1])

2


In [23]:
arr = np.array([1,22,33,44,55,66,77,88,99])

print(arr[3])

print(arr[6])

print(arr[8])

print("sum ", arr[3]+arr[6]+[8])

44
77
99
sum  [129]


# 2d array index

In [29]:
arr = np.array([[1,22,33,44],[55,66,77,88]])

print(arr[1,1])

66


# add the first element of row 1 and last element

In [31]:
arr = np.array([[1,22,33,44],[55,66,77,88]])


print(arr[0,0])
print(arr[1,3])
print(arr[0,0]+arr[1,3])

1
88
89


# access 3D arrays

# access the three element of the second array of the first array

In [5]:
arr = np.array([[[1,22,33,44],[55,66,77,88]],[[3,4,5,6],[99,66,77,88]]])

print(arr[0,1,2])

77


# Python Class Day 12/ 2nd Class of PanDa

# slicing of Numpy arrays

In [9]:
#2D array
import numpy as np


In [10]:
arr = np.array([1,2,3,4,5,6,7,8,9])
print(arr[::2])

[1 3 5 7 9]


# 2D array

In [11]:
arr = np.array([[12,13,14,15,16],[17,18,19,20,21]])

print(arr[1,1:4])

[18 19 20]


In [12]:
arr = np.array([[12,13,14,15,16],[17,18,19,20,21]])

print(arr[0,1:4])

[13 14 15]


# 3D array

In [15]:
arr = np.array([[[12,13,14,15,16],[17,18,19,20,21],[22,23,24,25,26]]])

print(arr[0,2,1:4])

[23 24 25]


# Checking the data type of an array

In [16]:
arr = np.array([1,2,3,4])


print(arr.dtype)

int32


In [20]:
arr = np.array(['array'])

print(arr.dtype)

<U5


# creating arrays with a defined data type

In [25]:
a = np.array([1,2,3,4], dtype = "S")

print(a)

print(a.dtype)

[b'1' b'2' b'3' b'4']
|S1


# create an array with data type 4 bytes int

In [26]:
a = np.array([1,2,3,4], dtype = "i4")

print(a)

print(a.dtype)

[1 2 3 4]
int32


# NumPy array shape

# the shape of an array is the number of element in each dimesnion

# print the shape of a 2d array

In [30]:
a = np.array([[1,2,3,4],[5,6,7,8]])

print(a.shape)

(2, 4)


In [31]:
a = np.array([[[1,2,3,4],[5,6,7,8],[9,7,8,6]]])

print(a.shape)

(1, 3, 4)


# join NumPy arrays

In [33]:
a = np.array([1,2,3,4])

a1 = np.array([5,6,7,8])


arr = np.concatenate((a,a1))

print(arr)

[1 2 3 4 5 6 7 8]


# join 2D array

In [35]:
a = np.array([[1,2,3,4],[5,6,7,8]])

a1 = np.array([[1,2,66,4],[5,6,44,8]])

a2 = np.concatenate((a,a1),axis =1)
print(a2)

[[ 1  2  3  4  1  2 66  4]
 [ 5  6  7  8  5  6 44  8]]


In [36]:
a = np.array([[1,2,3,4],[5,6,7,8]])

a1 = np.array([[1,2,66,4],[5,6,44,8]])

a2 = np.concatenate((a,a1),axis =0)
print(a2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 1  2 66  4]
 [ 5  6 44  8]]


# splitting array NumPy

# array in 3 part

In [37]:
a = np.array([1,2,3,4,5,6])

newa = np.array_split(a,3)

print(newa)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [38]:
a = np.array([1,2,3,4,5,6])

newa = np.array_split(a,4)

print(newa)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


# ravel & flatten

# converts multidimensional array into 1d array

In [43]:
a = np.array([[[1,2,3,4],[5,6,7,8],[4,5,6,7]]])

print(a)

print(a.ndim)

n =a.ravel()
print(n)
print("new dimensions ", n.ndim)

[[[1 2 3 4]
  [5 6 7 8]
  [4 5 6 7]]]
3
[1 2 3 4 5 6 7 8 4 5 6 7]
new dimensions  1


In [45]:
a = np.array([[[1,2,3,4],[5,6,7,8],[4,5,6,7]]])

print(a)

print(a.ndim)

n =a.flatten()
print(n)
print("new dimensions ", n.ndim)

[[[1 2 3 4]
  [5 6 7 8]
  [4 5 6 7]]]
3
[1 2 3 4 5 6 7 8 4 5 6 7]
new dimensions  1


In [51]:
a = np.array([[[[1,2,3],[33,44,55],[44,55,77],[55,99,77]]]])


print(a)


print("Dimensnion ",a.ndim)
s = a.ravel()

print(s)

print(s.ndim)

[[[[ 1  2  3]
   [33 44 55]
   [44 55 77]
   [55 99 77]]]]
Dimensnion  4
[ 1  2  3 33 44 55 44 55 77 55 99 77]
1


# Unique function

In [52]:
a = np.array([1,2,333,444,55,343,53,545,66,77,88,1,2,333,444])



print(a)


s = np.unique(a)

print(s)

[  1   2 333 444  55 343  53 545  66  77  88   1   2 333 444]
[  1   2  53  55  66  77  88 333 343 444 545]


In [53]:
a = np.array([1,2,333,444,55,343,53,545,66,77,88,1,2,333,444])



print(a)


s = np.unique(a, return_index = True)

print(s)

[  1   2 333 444  55 343  53 545  66  77  88   1   2 333 444]
(array([  1,   2,  53,  55,  66,  77,  88, 333, 343, 444, 545]), array([ 0,  1,  6,  4,  8,  9, 10,  2,  5,  3,  7], dtype=int64))


In [55]:
a = np.array([1,2,333,444,55,343,53,545,66,77,88,1,2,333,444])



print(a)


s = np.unique(a, return_index = True, return_counts = True)

print(s)

[  1   2 333 444  55 343  53 545  66  77  88   1   2 333 444]
(array([  1,   2,  53,  55,  66,  77,  88, 333, 343, 444, 545]), array([ 0,  1,  6,  4,  8,  9, 10,  2,  5,  3,  7], dtype=int64), array([2, 2, 1, 1, 1, 1, 1, 2, 1, 2, 1], dtype=int64))


# Delete

In [56]:
a = np.array([1,2,3,4,5])


s = np.delete(a,[1])

print(s)

[1 3 4 5]


In [58]:
a = np.array([[1,2,3,4],[5,55,6,7],[2,444,55,66]])

print(a)

s = np.delete(a,1,axis = 0)

print()

print(s)

[[  1   2   3   4]
 [  5  55   6   7]
 [  2 444  55  66]]

[[  1   2   3   4]
 [  2 444  55  66]]
